### ISSUE TITLE
Invalid compression_type 5 detected!

### ISSUE THREAD

**Issue by netomx** [waynepiekarski/zimHttpServer32#4]
As title, trying to use wikipedia_es_history_maxi_2024-01.zim

Any ideas?

**Comment by waynepiekarski** [comment]
From the sounds of the error message, wikipedia is using a new ZIM compression format. The code in my repository is 7 years old and I no longer use it, and won't support this new format. With the arrival of the Raspberry Pi Zero W a few years ago, it is now possible to use a real ZIM server written in C/C++ and have enough memory available. So I would give something like https://wiki.kiwix.org/wiki/Kiwix-serve a try.

**Comment by kelson42** [comment]
I guess LZMA.
